spring:
  main:
    banner-mode: "off"
    log-startup-info: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    data: classpath:data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---
logging:
  file:
    path: ${LOG_FILE:/usr/local/dev/talkative}
    
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS, JST} ${LOG_LEVEL_PATTERN:-%5p} --- [%t] %-40.40logger{39} : %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS, JST} ${LOG_LEVEL_PATTERN:-%5p} --- [%t] %-40.40logger{39} : %m%n"
  level:
    com.shinstealer.craft:  ${LOG_LEVEL:INFO}

---
spring:
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    template-resolver-order: 0

